"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const oficinaMecanica_1 = require("./oficinaMecanica");
const ConsertoVeiculo_1 = require("./ConsertoVeiculo");
const car = new oficinaMecanica_1.ModeloCarro(102548, 'Fiat', 'Punto', 2025);
const con = new ConsertoVeiculo_1.Consertar(11213, 'I30', 'Hynday', 2025, 'Preto');
console.log(car.getExibirVeiculo());
console.log("============================");
car.mover();
car.carLigado();
con.fazerSom();
console.log("============================");
