"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const baleia_1 = require("./baleia");
const morcego_1 = require("./morcego");
const mor = new morcego_1.Morcego('Motta', 'stringFOX', 'amarela');
const bal = new baleia_1.Baleia('Filotão', 'barriga branca', 'preta');
bal.comer('peixes');
mor.comer('Banana');
console.log("\n" + "=".repeat(40) + "\n");
console.log(mor.voar());
console.log(bal.nadar());
console.log("\n" + "=".repeat(40) + "\n");
